// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_interface.go -package=handler
//

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	models "github.com/libraryManagementSystem/models"
	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockBookServicer is a mock of BookServicer interface.
type MockBookServicer struct {
	ctrl     *gomock.Controller
	recorder *MockBookServicerMockRecorder
}

// MockBookServicerMockRecorder is the mock recorder for MockBookServicer.
type MockBookServicerMockRecorder struct {
	mock *MockBookServicer
}

// NewMockBookServicer creates a new mock instance.
func NewMockBookServicer(ctrl *gomock.Controller) *MockBookServicer {
	mock := &MockBookServicer{ctrl: ctrl}
	mock.recorder = &MockBookServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookServicer) EXPECT() *MockBookServicerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBookServicer) Add(c *gofr.Context, isbn int, title, author string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", c, isbn, title, author)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBookServicerMockRecorder) Add(c, isbn, title, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBookServicer)(nil).Add), c, isbn, title, author)
}

// Borrow mocks base method.
func (m *MockBookServicer) Borrow(arg0 *gofr.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Borrow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Borrow indicates an expected call of Borrow.
func (mr *MockBookServicerMockRecorder) Borrow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Borrow", reflect.TypeOf((*MockBookServicer)(nil).Borrow), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockBookServicer) List(arg0 *gofr.Context, arg1 int) (*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBookServicerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookServicer)(nil).List), arg0, arg1)
}

// ListAvailible mocks base method.
func (m *MockBookServicer) ListAvailible(arg0 *gofr.Context) ([]*models.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailible", arg0)
	ret0, _ := ret[0].([]*models.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailible indicates an expected call of ListAvailible.
func (mr *MockBookServicerMockRecorder) ListAvailible(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailible", reflect.TypeOf((*MockBookServicer)(nil).ListAvailible), arg0)
}

// Remove mocks base method.
func (m *MockBookServicer) Remove(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockBookServicerMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockBookServicer)(nil).Remove), arg0, arg1)
}

// Returnbook mocks base method.
func (m *MockBookServicer) Returnbook(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Returnbook", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Returnbook indicates an expected call of Returnbook.
func (mr *MockBookServicerMockRecorder) Returnbook(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Returnbook", reflect.TypeOf((*MockBookServicer)(nil).Returnbook), arg0, arg1)
}

// MockUserServicer is a mock of UserServicer interface.
type MockUserServicer struct {
	ctrl     *gomock.Controller
	recorder *MockUserServicerMockRecorder
}

// MockUserServicerMockRecorder is the mock recorder for MockUserServicer.
type MockUserServicerMockRecorder struct {
	mock *MockUserServicer
}

// NewMockUserServicer creates a new mock instance.
func NewMockUserServicer(ctrl *gomock.Controller) *MockUserServicer {
	mock := &MockUserServicer{ctrl: ctrl}
	mock.recorder = &MockUserServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServicer) EXPECT() *MockUserServicerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserServicer) Add(arg0 *gofr.Context, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockUserServicerMockRecorder) Add(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserServicer)(nil).Add), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockUserServicer) List(arg0 *gofr.Context, arg1 int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserServicerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserServicer)(nil).List), arg0, arg1)
}

// ListAll mocks base method.
func (m *MockUserServicer) ListAll(arg0 *gofr.Context) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", arg0)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockUserServicerMockRecorder) ListAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockUserServicer)(nil).ListAll), arg0)
}

// Remove mocks base method.
func (m *MockUserServicer) Remove(arg0 *gofr.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockUserServicerMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockUserServicer)(nil).Remove), arg0, arg1)
}
